Repository AY2324S1-CS2103T-T09-4/tp, pull requests merged in 2023-11, with the labels that each got.

#97 Enhance markAttendance Command
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
Labels: type.enhancement, priority.medium, 1.3b

#98 Implement merge command
  docs/UserGuide.md
  docs/images/mergeCommand.png
  src/main/java/seedu/address/logic/commands/MergeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MergeCommandParser.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/MergeCommandTest.java
  src/test/java/seedu/address/logic/parser/MergeCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.enhancement, priority.medium, 1.3b

#101 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/model/person/Attendance.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.documentation, priority.medium, 1.3b

#99 Implement attendance saving
  docs/UserGuide.md
  docs/images/deleteAll.png
  docs/images/listAttendance.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CourseCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentsCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CourseCommandParser.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/week/Week.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/ListStudentsCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.enhancement, 1.3b

#103 Update UserGuide.md, fixed #71, #100, #102 and improve tests
  docs/UserGuide.md
  docs/images/addFilter.png
  docs/images/filterClear.png
  src/main/java/seedu/address/commons/core/FilterSettings.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CourseCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CourseCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/AddressBookManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/commands/CourseCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/MergeCommandTest.java
  src/test/java/seedu/address/logic/parser/CourseCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookManagerTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.documentation, type.enhancement, 1.3b

#104 Update UserGuide.md
  docs/UserGuide.md
  docs/images/addContact.png
  docs/images/courseCreate.png
  docs/images/courseDelete.png
  docs/images/courseEdit.png
  docs/images/courseSwitch.png
  docs/images/deleteContact.png
  docs/images/editContact.png
  docs/images/findAlexDavidResult.png
  docs/images/findCommand.png
  docs/images/listStudents.png
  docs/images/markAttendance.png
Labels: type.documentation

#153 Update `mark` Command Documentation
  docs/UserGuide.md
Labels: priority.high, v1.4

#155 Bug Fixes for v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSeqDiagram.puml
  docs/diagrams/MarkAttendanceCommandActivityDiagram.puml
  docs/diagrams/ViewActivityDiagram.puml
  docs/diagrams/ViewSeqDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSeqDiagram.png
  docs/images/MarkAttendanceActivityDiagram.png
  docs/images/ViewActivityDiagram.png
  docs/images/ViewSeqDiagram.png
  docs/images/viewCommand.png
  docs/team/anthonytamzil.md
  src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.documentation, type.enhancement, v1.4

#154 Bug Fixes for v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MergeActivityDiagram.puml
  docs/diagrams/MergeSeqDiagram.puml
  docs/images/MergeActivityDiagram.png
  docs/images/MergeSeqDiagram.png
  docs/team/fuyiqiao.md
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.documentation, type.enhancement, v1.4

#159 Update PPP, DG, UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MarkAttendanceSeqDiagram.puml
  docs/images/MarkAttendanceSeqDiagram.png
  docs/team/zjinnnn.md
Labels: type.documentation, v1.4

#158 Bug Fixes for v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/clear.png
  docs/images/viewCommand.png
  docs/team/spatuly.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/predicate/ContainsTagPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/MergeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.documentation, type.enhancement, v1.4

#161 Update PPP
  docs/team/elgintzm.md
Labels: type.documentation, v1.4

#163 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/DeleteAllSeqDiagram.puml
  docs/diagrams/ListAttendanceActivityDiagram.puml
  docs/diagrams/ListAttendanceSeqDiagram.puml
  docs/images/DeleteAllSeqDiagram.png
  docs/images/ListAttendanceActivityDiagram.png
  docs/images/ListAttendanceSeqDiagram.png
  docs/team/spatuly.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: type.documentation, v1.4

#165 Update PPP
  docs/team/anthonytamzil.md
Labels: type.documentation, v1.4

#168 Fix #162, update UserGuide.md and DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/elgintzm.md
  src/main/java/seedu/address/model/AddressBookManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.documentation

#172 Update UserGuide.md, DeveloperGuide.md, revert Name MESSAGE_CONSTRAINT
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CourseCommandSeqDiagram.puml
  docs/images/CourseCommandSeqDiagram.png
  docs/images/Ui.png
  src/main/java/seedu/address/model/person/Name.java
Labels: type.documentation

#171 v1.4 updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/fuyiqiao.md
  src/main/java/seedu/address/logic/commands/MergeCommand.java
Labels: type.documentation, v1.4

#174 Update UserGuide.md
  docs/UserGuide.md
Labels: type.documentation

#175 Update PPP & UG
  docs/UserGuide.md
  docs/team/zjinnnn.md
Labels: type.documentation

#173 Update test cases and DG diagrams, improve code quality
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteAllSeqDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ListAttendanceSeqDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteAllSeqDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ListAttendanceSeqDiagram.png
  docs/team/spatuly.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/predicate/AbsentFromTutorialPredicate.java
  src/main/java/seedu/address/model/predicate/ContainsTagPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/model/predicate/AbsentFromTutorialPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: v1.4

#177 Update PPP
  docs/team/zjinnnn.md
Labels: type.documentation
