Repository AY2324S1-CS2103T-T09-4/tp, pull requests merged in 2023-10, with the labels that each got.

#42 Update DG, AboutUs and PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/anthonytamzil.png
  docs/team/anthonytamzil.md
Labels: type.documentation, 1.1

#41 Update AboutUs and PPP
  README.md
  docs/AboutUs.md
  docs/images/zjinnnn.png
  docs/team/zjinnnn.md
Labels: type.documentation, 1.1

#38 Update README
  README.md
  docs/images/TAvigator LogoBanner (Dark Theme).png
  docs/images/TAvigator LogoBanner (Light Theme).png
Labels: type.documentation, 1.1

#48 Update AboutUs and PPP
  docs/AboutUs.md
  docs/images/elgintzm.png
  docs/team/elgintzm.md
Labels: type.documentation, 1.1

#43 Update DG
  docs/DeveloperGuide.md
Labels: type.documentation, 1.1

#47 Update UG
  docs/UserGuide.md
Labels: type.documentation, 1.1

#53 Update DG
  docs/DeveloperGuide.md
Labels: type.documentation, 1.1

#51 Update UG
  docs/UserGuide.md
Labels: type.documentation, 1.1

#54 Update UG and DG with use cases
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation, 1.1

#56 Remove traces of AB3
  docs/UserGuide.md
  docs/_config.yml
  docs/images/johndoe.png
  docs/team/johndoe.md
Labels: type.documentation, 1.1

#57 Remove Traces of AddressBook from User Guide
  docs/UserGuide.md
Labels: type.documentation

#58 feat: Add MarkAttendance Command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/ID.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: 1.2, priority.high, type.story

#60 Refactor by removing Address
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.enhancement, 1.2, priority.high

#61 Modified Find Command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/ID.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.enhancement, 1.2, priority.high

#74 tests: Add MarkAttendanceCommandTest, MarkAttendanceCommandParserTest, AttendanceTest, IDTest
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/test/java/seedu/address/logic/commands/ListAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/MarkAttendanceCommandParserTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/model/person/IdTest.java
  src/test/java/seedu/address/model/predicate/AbsentFromTutorialPredicateTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.enhancement, 1.2, priority.high

#75 Add FindCommandParser Test Cases
  README.md
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ID.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/tavigator.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.enhancement, 1.2, priority.high

#73 Add tests for FilterCommand and update UserGuide
  docs/UserGuide.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/predicate/ContainsTagPredicateTest.java
  src/test/java/seedu/address/model/predicate/IdContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.documentation, type.enhancement, 1.2

#76 Bug Fix: Test Cases failing for invalid IDs
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ID.java
  src/test/java/seedu/address/model/person/IdTest.java
Labels: bug, 1.2, priority.high

#80 Enhance MarkAttendanceCommand and MarkAttendanceCommandParser
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/MarkAttendanceCommandParserTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.enhancement, priority.high, type.story, 1.3

#78 Add delete all functionality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/ListAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentsCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/predicate/AbsentFromTutorialPredicate.java
  src/main/java/seedu/address/model/predicate/ContainsTagPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/model/predicate/AbsentFromTutorialPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.enhancement, priority.high, 1.3

#85 Add Reason of Absence to Attendance
  build.gradle
  docs/UserGuide.md
  docs/images/addContact.png
  docs/images/addFilter.png
  docs/images/clear.png
  docs/images/deleteAll.png
  docs/images/deleteContact.png
  docs/images/editContact.png
  docs/images/filterClear.png
  docs/images/findCommand.png
  docs/images/listAttendance.png
  docs/images/listStudents.png
  docs/images/markAttendance.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/week/Week.java
  src/test/java/seedu/address/logic/commands/ListAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkAttendanceCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TalliedAttendanceTest.java
  src/test/java/seedu/address/model/predicate/AbsentFromTutorialPredicateTest.java
  src/test/java/seedu/address/model/week/WeekTest.java
Labels: type.enhancement, priority.high, type.story, 1.3

#88 Update list and delete commands and add DG
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ListAttendanceSeqDiagram.puml
  docs/diagrams/ListCommandClassDiagram.puml
  docs/diagrams/ListStudentsSeqDiagram.puml
  docs/images/ListAttendanceSeqDiagram.png
  docs/images/ListStudentsSeqDiagram.png
  docs/images/listAttendance.png
  docs/team/anthonytamzil.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/ListAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/predicate/AbsentFromTutorialPredicate.java
  src/main/java/seedu/address/model/predicate/ContainsTagPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/predicate/AbsentFromTutorialPredicateTest.java
  src/test/java/seedu/address/model/predicate/ContainsTagPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.documentation, 1.3

#90 Update DeveloperGuide
  docs/DeveloperGuide.md
  docs/diagrams/MarkAttendanceCommandActivityDiagram.puml
  docs/images/MarkAttendanceActivityDiagram.png
Labels: type.documentation, 1.3

#91 docs: update dg
  docs/DeveloperGuide.md
  docs/images/ListCommandClassDiagram.png
Labels: type.documentation, 1.3

#94 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.documentation

#92 Add View Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/test/java/seedu/address/logic/commands/ListAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MarkAttendanceCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TalliedAttendanceTest.java
  src/test/java/seedu/address/model/predicate/AbsentFromTutorialPredicateTest.java
Labels: type.documentation, type.enhancement, 1.3

#95 Edit ug
  docs/UserGuide.md
Labels: type.documentation, 1.3

#96 Add support for multiple address books
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CourseCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CourseCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/AddressBookManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBookManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/CourseListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/CourseListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CourseCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/ListStudentsCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/AddressBookManagerBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.enhancement, 1.3
